/*Aurora "Ro" Bulcock
 * COSC 1337 001
 * 11/15/2023
 * Purpose: To encapsulate information about a Train (Program 5 Trains)
 */
package trainsDemo;

import java.util.ArrayList;

/**Encapsulates information about an individual train
 * 
 */
public class Train {
	/**The name of the train*/
	private String name;
	/**A list of all passengers on this train*/
	private ArrayList<Passenger> passengers;

	/**Creates a new train with input information
	 * @param name The name of the train
	 */
	public Train(String name) {
		setName(name);
		passengers = new ArrayList<Passenger>();
	}

	/**Returns the train name
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**Sets the name of this Train
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**Adds a passenger to the list of Passengers and returns the size of the list
	 * @param passenger The Passenger to be added
	 * @return the number of Passengers on the train so far*/
	public int addPassenger(Passenger passenger) {
		passengers.add(passenger);
		return passengers.size();
	}

	/**Returns the percentage of Passengers traveling in first class
	 * 
	 * @return the percentage of Passengers in first class
	 */
	public double getPercentInFirstClass() {
		int generalCount = 0;
		int firstClassCount = 0;
		for (Passenger currentPassenger:passengers) {
			generalCount++;
			if (currentPassenger.isFirstClass())
				firstClassCount++;
		}
		return (double)firstClassCount/generalCount;
	}

	/**Returns the total revenue generated by this train
	 * 
	 * @param priceForFirstClass Ticket price for First Class
	 * @param regularPrice Ticket price for regular ticket
	 * @return the total revenue generated by this Train
	 */
	public double getTrainRevenue(double priceForFirstClass, double regularPrice) {
		double total = 0;
		for (Passenger currentPassenger:passengers)
			if (currentPassenger.isFirstClass())
				total += priceForFirstClass;
			else total += regularPrice;
		return total;
	}

	/**Returns true iff nameOfPassenger is on this Train
	 * 
	 * @param nameOfPassenger The name of the passenger
	 * @return true iff nameOfPassenger is on this Train
	 */
	public boolean isPassengerOnTrain(String nameOfPassenger) {
		for (Passenger currentPassenger:passengers)
			if (currentPassenger.getName().equals(nameOfPassenger))
				return true;
		return false;
	}

	/**Return true iff the two objects should be considered equal
	 * 
	 * @param o The object to compare this to
	 * @return True iff the two objects should be considered equal
	 */
	@Override
	public boolean equals(Object o) {
		return toString().equals(o.toString());
	}

	/**Returns a string version of this Train
	 * @return a String version of this Train
	 */
	@Override
	public String toString() {
		String returnString = getName()+":\n";
		int number = 1;
		for (Passenger current:passengers)
			returnString += (number++)+" - "+current+"\n";
		return returnString;

	}
}
